repos:
  - repo: https://github.com/psf/black
    rev: ''
    hooks:
      - id: black
        args: [ "--line-length", "140" ]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: ''
    hooks:
      - id: isort
        args: [ "--profile", "black", "--filter-files" ]
  - repo: https://github.com/pycqa/flake8
    rev: ''
    hooks:
      - id: flake8
        args: [--max-line-length=140]
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
        pass_filenames: false
        files: \.(py)$
        exclude: migrations/, venv/, .git/
