# Generated by Django 4.2.1 on 2023-05-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("phone_number", models.CharField(max_length=15)),
                ("code", models.CharField(max_length=6)),
                ("expiration_time", models.DateTimeField()),
                ("device_id", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Verification code",
                "verbose_name_plural": "Verification codes",
                "unique_together": {("phone_number", "code")},
            },
        ),
    ]
