# Generated by Django 4.2.1 on 2023-05-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationcode",
            name="full_name",
            field=models.CharField(default="fuck you", max_length=128),
            preserve_default=False,
        ),
    ]
