# Generated by Django 4.2.1 on 2023-05-16 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("verification", "0002_verificationcode_full_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verificationcode",
            name="full_name",
        ),
    ]
