# Generated by Django 4.2.1 on 2023-05-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verification", "0004_verificationcode_full_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="verificationcode",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="verificationcode",
            name="type",
            field=models.CharField(
                choices=[("ver", "Verification"), ("res", "Password Reset")],
                default="ver",
                max_length=3,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="verificationcode",
            unique_together={("phone_number", "code", "type", "device_id")},
        ),
    ]
