# Generated by Django 4.2.1 on 2023-05-18 11:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("verification", "0005_alter_verificationcode_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verificationcode",
            name="full_name",
        ),
    ]
