# Generated by Django 4.2.1 on 2023-05-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                default=998912958899,
                max_length=15,
                unique=True,
                verbose_name="Phone number",
            ),
            preserve_default=False,
        ),
    ]
