# Generated by Django 4.2.1 on 2023-05-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_remove_user_first_name_remove_user_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Is user deleted?"),
        ),
    ]
