# Generated by Django 4.2.1 on 2023-05-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_user_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Is user phone number verified?"),
        ),
    ]
