# Generated by Django 4.2.1 on 2023-05-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allowed_to_reset",
            field=models.BooleanField(
                default=False, verbose_name="Is user allowed to reset password?"
            ),
        ),
    ]
